### ISSUE TITLE
How to handle optional query parameters ?

### ISSUE THREAD

**Issue by lorefnon** [rcs/route-parser#13]
I had assumed query parameters to always be optional. However that does not seem to be the case. 

So I wanted to know if it is possible to define a single root level route which can handle two optional parameters (say `q1` and `q2`): 

I have tried the following: 
- `new Route('/?q1=:q1&q2=:q2')` Seems to treat both parameters as mandatory
- `new Route('/?(q1=:q1)&(q2=:q2)')` Does not match `/` 
- `new Route('/(?(q1=:q1)&(q2=:q2)'))` Reverse routing is not able to populate the query params. 

Is there something I am doing wrong ?

**Comment by ivan-kleshnin** [comment]
@lorefnon if params are optional you shouldn't define them in the route.
Route mask is about *what is expected to be* (by definition!). 
Same reasoning applies for URL params and QS params.

**Comment by lorefnon** [comment]
> Route mask is about what is expected to be (by definition!). 

The readme explicitly describes the usage of `()` for optional groups: 
>  Optional group that doesn't have to be part of the query. Can contain nested optional groups, params, and splats

It would be nice to have an analogous facility for query parameters.

**Comment by Marak** [comment]
It seems to me if you want more advanced validation on query string parameters, you might want to implement a separate schema mechanism.

What I usually do is export a schema per View for the expected input variables. Validate after the route is triggered. These could be query string, but I usually merge all possible input parameters into a common scope ( form + query + json, etc).

This way, you can have optional parameters / default values / custom validators etc.

Better to keep the route parameters more constant. Variable route parameters can get a bit tricky.

**Comment by ivan-kleshnin** [comment]
> The readme explicitly describes the usage of () for optional groups:

Optional groups are here because you need to define the required path part of the mask after them.
Path fragments are sequential. Params and query params are not.
That's the difference.

**Comment by lorefnon** [comment]
@ivan-kleshnin This is understandable but orthogonal to the original context.

The primary reason path fragments are sequential is that they can be used to encode hierarchical relationships leading to a resource. eg: `/company/1/employees/2`

Query parameters are non-sequential and hence they can be used for identifying the resource from non-hierarchical data. eg: `/employees?designation=senior_architect&experience_gt=20`

Now I would expect a route to be a definitive locator to a single resource or a collection of resources. It is very much possible that it the resource(s) can be uniquely identified through a single hierarchy of relationships or a set of non-hierarchical relations or a combination of the two. 

So if facilitating optional path parameters makes sense so does facilitating optional query parameters.

**Comment by ivan-kleshnin** [comment]
I continue to disagree. There is no optional path params per se. There is just an ability to prepend required params with some stuff.

**Comment by shepmaster** [comment]
For another perspective, this makes me sad because I can no longer use `route.reverse` to generate a URL. I have to call `route.reverse`, *reparse the URL* if there are some mandatory query parameters added, then add my optional parameters in some fashion.

I agree that the ability to have optional path *parameters* seems to indicate that I should be able to add optional query parameters.

> Route mask is about what is expected to be (by definition!).

Perhaps the README should be updated to indicate that this is the design decision of the library: that it only intends to match the things that are required (except for the optional parts, which aren't).

> Maybe you should start making more resource endpoints instead of reassigning them?

This isn't always an achievable goal when replacing existing software. It also isn't always a valid design decision on its own; consider the quintessential example of a search page or sorting / paging a list. While it is possible to encode that information in a hierarchical manner, it doesn't necessarily make any more sense than non-hierarchically.

**Comment by Marak** [comment]
I'd suggest trying to resolve the issue in a Fork.

Probably not as easy as it may seem.

**Comment by lorefnon** [comment]
Seeing that the project owners somehow did not find it a valid use case, what I had ended up doing was using this library for path parsing and named routing and [qs](https://www.npmjs.com/package/qs) for parsing and stringifying query parameters. 

It sufficed for my use case.

**Comment by shepmaster** [comment]
Deciding what the library will and will not do is 100% the maintainers prerogative. I'd still encourage them to resolve this issue by explicitly stating design goals (and non-goals) in the README. Potentially even calling out that the feature of optional query parameters is not supported — the two of us were proactive enough to communicate here, how many others were not?

This may also reduce support burden, preventing other people from opening new issues.

**Comment by rcs** [comment]
I'd love to expand this out to include optional query parameters. I'm uncertain of what the API would look like, and would love to discuss _any_ PRs or API examples y'all have found or wanted.

One of the pieces that's just not covered by the approach taken here is the fact that we expect query parameters to not be positional. e.g. `foo?bar&baz` is generally regarded as equivalent to `foo?baz&bar`. We don't have anything here to actually cover that.
