### ISSUE TITLE
Support for unnamed splats

### ISSUE THREAD

**Issue by niftylettuce** [rcs/route-parser#15]
If we don't name our splats, e.g. if we are testing the route of `/rcs/route-parser/158172398` with a pattern of `/rcs/route-parser/*`, the `*` splat won't be matched to `158172398` and it will return `false`.  Instead I'd like anonymous splats to be matched.  Related to my issues with https://github.com/snd/url-pattern/issues/24.

**Comment by rcs** [comment]
Thanks for writin' in.

Could you help me understand what you want? For this use case, why don't you want to name the splat?

**Comment by niftylettuce** [comment]
It's part of an admin management page - the permission thing I built lets you put in `*` wildcards for routes, like `/github/admin/*` for all routes/methods with that path.   Guess I could string replace with letters of alphabet for each wildcard in this string `/github/admin/*` (so it'd be like a `str.replace` for each `*` with a `*{{someLetterOrNumber}}`.  I decided to use the `url-pattern` library as it more closely matched what I was looking for - except I had to then add the trailing slashes via `connect-slashes` in order to make it work 100%.
