### ISSUE TITLE
Route Parser returns false, don't know why

### ISSUE THREAD

**Issue by mschipperheyn** [rcs/route-parser#18]
I have a route like so:

    const path = '/account/json/wall/post/:id/comments/?start=:start&max=:max';

I call this with an object

    const vars = {
      id:50,
      start:0,
      max:12
    };

    return new Route(path).reverse(vars);

It returns false?

**Comment by mschipperheyn** [comment]
So, yeah, I found the bug. route-parser will accept a number if there is only one key in the object, but not if there are more. :-(

Time to get some new kevlar!

**Comment by rcs** [comment]
Thank you for this! I think I said "bullet proof" before I added reversing... Should be fixed in master. I think I'm going to take a pass at query params and updating dev dependencies before cutting a new version for NPM.

Let me know if that doesn't work for you.
