### ISSUE TITLE
Problems with webpack

### ISSUE THREAD

**Issue by haihappen** [rcs/route-parser#2]
It's seems that the compiled-grammer is not webpack-ready.

```
Module not found: Error: Cannot resolve module 'fs' in ./node_modules/route-parser/lib/route
 @ ./~/route-parser/lib/route/compiled-grammar.js 617:17-30
```

**Comment by rcs** [comment]
Thanks for the report. A basic jison parser generate() generates a module that has a main() function to use as a command line wrapper. We don't need that here, and it's been removed.

**Comment by haihappen** [comment]
Cool!
