### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by Marak** [rcs/route-parser#7]
Everything worked better than expected.

Thank you!

+9000

**Comment by rcs** [comment]
Thank you! Happy to hear it!

**Comment by ivan-kleshnin** [comment]
I second this. 

I just wanted to find **no-bullshit** route matching library (no frameworks, no callbacks, no nested routes, no `window.location` checks etc.). At the same time, I wanted reverse URL mechanics. 

Congrats on nailing that balance.
