### ISSUE TITLE
enable `route instanceof Route`

### ISSUE THREAD

**Issue by CezaryDanielNowak** [rcs/route-parser#9]
Ideal code would be:
```
let Route = require('route-parser')
let routeInst = new Route('/.../')
if (routeInst instanceof Route) {
   ...
}
```

**Comment by Marak** [comment]
Why?

**Comment by CezaryDanielNowak** [comment]
It's weird when `(new X()) instanceof X` is false, and I had this use-case in my code :-)

**Comment by Marak** [comment]
I see now.

Generally, I'd recommend trying to avoid the usage of `instanceof` in JavaScript completely in your code ( with the exception of checking if an `Object` is an `Array` )

If you are in a situation where you need to run something like:

```
if (routeInst instanceof Route) {
```

it usually indicates a not-so-great design choice that caused you need to perform the custom type check in the first place.

Just my opinion though.

**Comment by CezaryDanielNowak** [comment]
@Marak but still it's better to implement not-so-great design choice by
`if (routeInst instanceof Route) {`
instead of
`if (routeInst && routeInst .spec && routeInst .ast) {`

**Comment by Marak** [comment]
Better to not perform custom type check at all. 

If there is conditional on creation of object instance or conditional based on type of object, there is suboptimal architecture choice. You should already know whether or not object is of specific type at construction time.

**Comment by Lokua** [comment]
I agree with @CezaryDanielNowak. The suggested avoidance of using `instanceof`, while it may be good advice, doesn't really validate why `new Route()` doesn't return an instance of `Route`.  I'd expect the child of a constructor to pass the instanceof check. Why not use simple class pattern?

```js
function Route(spec) {

  // allow instantiation without `new`
  if (!(this instanceof Route)) return new Route(spec)

  // ... existing implementation, subbing `route` with `this`
}

Route.prototype.match = function (path) {/* ... */}

// etc.

module.exports = Route
```

This way `new Route() instanceof Route` and `Route() instanceof Route` both evaluate to true. Besides passing instanceof, wouldn't everything work the same as it is?

**Comment by Lokua** [comment]
Oops sorry to blab. just saw https://github.com/rcs/route-parser/pull/10. I guess that does it too ;)

**Comment by rcs** [comment]
Thanks for the input, @Lokua. Second person on this one means the people have spoken. We'll run with this at least until someone else complains :-) #10 has been merged.
